name: plr_meson Windows experiments
run-name: Testing Creating PL/R using meson
on: [push]
jobs:
  build_test_install:
    name: ${{ matrix.compiler }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      # Disable fail-fast as we want results from all even if one fails.
      fail-fast: false
      matrix:
        include:
          - compiler: UCRT64
            os: windows-latest

#         - compiler: cygwin
#           os: windows-latest
# 
#         - compiler: msvc
#           os: windows-latest
    steps:
      - name: Matrix Verification
        if: matrix.os == 'windows-latest'
        run: |
          # systeminfo
          echo "${{ matrix.compiler }} on ${{ matrix.os }}"
#         if( Test-Path "C:\Program Files\PostgreSQL\16" ) { "pg x64-16 exists."  } else {  "pg x64-16 not exists." }
#         if( Test-Path "C:\Program Files\PostgreSQL\15" ) { "pg x64-15 exists."  } else {  "pg x64-15 not exists." }
          if( Test-Path "C:\Program Files\PostgreSQL\14" ) { "pg x64-14 exists."  } else {  "pg x64-14 not exists." } # ONLY THIS EXISTS
#         if( Test-Path "C:\Program Files\PostgreSQL\13" ) { "pg x64-13 exists."  } else {  "pg x64-13 not exists." }
#         if( Test-Path "C:\Program Files\PostgreSQL\12" ) { "pg x64-12 exists."  } else {  "pg x64-12 not exists." }
#         if( Test-Path "C:\Program Files\PostgreSQL\11" ) { "pg x64-11 exists."  } else {  "pg x64-11 not exists." }
#         if( Test-Path "C:\Program Files\PostgreSQL\10" ) { "pg x64-10 exists."  } else {  "pg x64-10 not exists." }
          function Set-EnvVar {param($X)     Add-Content -Path ${env:GITHUB_ENV} -Value "$X"}
          ${env:compiler} = "compiler"
          Set-EnvVar "compiler=${env:compiler}"

